-- 1. Profiles: add banner_url and bio
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS banner_url text;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS bio text;

-- 2. Custom Lists
CREATE TABLE IF NOT EXISTS custom_lists (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  name text not null,
  description text,
  is_public boolean default false,
  created_at timestamp with time zone default now()
);

CREATE TABLE IF NOT EXISTS custom_list_items (
  id bigint generated by default as identity primary key,
  list_id uuid references custom_lists(id) on delete cascade not null,
  media_id integer references media(id) on delete cascade not null,
  added_at timestamp with time zone default now(),
  unique(list_id, media_id)
);

-- Enable RLS
ALTER TABLE custom_lists ENABLE ROW LEVEL SECURITY;
ALTER TABLE custom_list_items ENABLE ROW LEVEL SECURITY;

-- Policies for custom_lists
CREATE POLICY "Public lists are viewable by everyone." ON custom_lists FOR SELECT USING (is_public = true OR auth.uid() = user_id);
CREATE POLICY "Users can insert own lists." ON custom_lists FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own lists." ON custom_lists FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own lists." ON custom_lists FOR DELETE USING (auth.uid() = user_id);

-- Policies for custom_list_items
CREATE POLICY "List items are viewable if list is public or owned." ON custom_list_items FOR SELECT USING (
  EXISTS (SELECT 1 FROM custom_lists WHERE id = custom_list_items.list_id AND (is_public = true OR user_id = auth.uid()))
);
CREATE POLICY "Users can insert own list items." ON custom_list_items FOR INSERT WITH CHECK (
  EXISTS (SELECT 1 FROM custom_lists WHERE id = custom_list_items.list_id AND user_id = auth.uid())
);
CREATE POLICY "Users can update own list items." ON custom_list_items FOR UPDATE USING (
  EXISTS (SELECT 1 FROM custom_lists WHERE id = custom_list_items.list_id AND user_id = auth.uid())
);
CREATE POLICY "Users can delete own list items." ON custom_list_items FOR DELETE USING (
  EXISTS (SELECT 1 FROM custom_lists WHERE id = custom_list_items.list_id AND user_id = auth.uid())
);

-- 3. Spoiler tags for reviews
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS is_spoiler boolean default false;

-- 4. Notifications
CREATE TABLE IF NOT EXISTS notifications (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  title text not null,
  message text not null,
  is_read boolean default false,
  created_at timestamp with time zone default now()
);

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage own notifications." ON notifications FOR ALL USING (auth.uid() = user_id);
