-- Dedup-Tabelle: verhindert mehrfache Benachrichtigung pro Episode.
CREATE TABLE IF NOT EXISTS public.episode_notifications (
  id               bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  media_id         integer     NOT NULL REFERENCES public.media(id) ON DELETE CASCADE,
  episode_air_date date        NOT NULL,
  created_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (media_id, episode_air_date)
);

COMMENT ON TABLE public.episode_notifications IS 'Dedup-Tracking für „neue Episode"-Notifications. Nur service_role (Edge Function) schreibt.';

-- RLS an, KEINE Policies: anon/authenticated haben keinen Zugriff,
-- nur die Edge Function (service_role) umgeht RLS.
ALTER TABLE public.episode_notifications ENABLE ROW LEVEL SECURITY;

-- Scheduler + Async-HTTP aktivieren.
CREATE EXTENSION IF NOT EXISTS pg_cron;
CREATE EXTENSION IF NOT EXISTS pg_net;

-- Bestehenden Job (falls vorhanden) entfernen, dann neu planen (idempotent).
DO $$
BEGIN
  PERFORM cron.unschedule('episode-notifier-daily');
EXCEPTION WHEN OTHERS THEN
  NULL;
END $$;

-- Täglich 06:00 UTC: ruft die Edge Function auf. Anon-Key kommt aus Vault
-- (Secret 'cron_anon_key' — kein Key in dieser Datei). Function-Auth via verify_jwt.
SELECT cron.schedule(
  'episode-notifier-daily',
  '0 6 * * *',
  $$
  SELECT net.http_post(
    url := 'https://phrpjjuhwvanqfzcfxxg.supabase.co/functions/v1/episode-notifier',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', 'Bearer ' || (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'cron_anon_key')
    ),
    body := '{}'::jsonb
  );
  $$
);

-- HINWEIS: Der Vault-Eintrag 'cron_anon_key' wird einmalig außerhalb dieser
-- Migration gesetzt (enthält den öffentlichen anon-Key):
--   select vault.create_secret('<ANON_KEY>', 'cron_anon_key', '...');
