-- ============================================================
--  02_tables.sql
--  Alle Tabellen der HORIZON-Datenbank.
--  ACHTUNG: Löscht bestehende Tabellen vollständig (CASCADE).
--  Zuerst 01_extensions.sql ausführen.
-- ============================================================

-- ----------------------------------------------------------
-- CLEANUP: Tabellen in umgekehrter Abhängigkeitsreihenfolge
-- ----------------------------------------------------------
DROP TABLE IF EXISTS notifications       CASCADE;
DROP TABLE IF EXISTS custom_list_items   CASCADE;
DROP TABLE IF EXISTS custom_lists        CASCADE;
DROP TABLE IF EXISTS reviews             CASCADE;
DROP TABLE IF EXISTS user_watchlist      CASCADE;
DROP TABLE IF EXISTS media               CASCADE;
DROP TABLE IF EXISTS profiles            CASCADE;

-- ----------------------------------------------------------
-- PROFILES
-- Nutzerprofile, verknüpft mit Supabase Auth.
-- Wird automatisch durch Trigger beim Signup befüllt.
-- ----------------------------------------------------------
CREATE TABLE profiles (
  id           uuid        PRIMARY KEY REFERENCES auth.users ON DELETE CASCADE,
  username     text        UNIQUE,
  avatar_url   text,
  banner_url   text,
  bio          text,
  updated_at   timestamptz NOT NULL DEFAULT now(),

  -- Username: 3-30 Zeichen, nur Buchstaben/Zahlen/Unterstrich
  CONSTRAINT username_length  CHECK (username IS NULL OR char_length(username) BETWEEN 3 AND 30),
  CONSTRAINT username_chars   CHECK (username IS NULL OR username ~ '^[a-zA-Z0-9_]+$'),
  -- Bio: maximal 500 Zeichen
  CONSTRAINT bio_length       CHECK (bio IS NULL OR char_length(bio) <= 500),
  -- URLs müssen mit http/https beginnen
  CONSTRAINT avatar_url_fmt   CHECK (avatar_url  IS NULL OR avatar_url  ~* '^https?://'),
  CONSTRAINT banner_url_fmt   CHECK (banner_url  IS NULL OR banner_url  ~* '^https?://')
);

COMMENT ON TABLE profiles IS 'Öffentliche Nutzerprofile, 1:1 zu auth.users.';
COMMENT ON COLUMN profiles.username IS '3-30 Zeichen, alphanumerisch + Unterstrich. Wird beim Signup aus raw_user_meta_data gezogen.';

-- ----------------------------------------------------------
-- MEDIA
-- Cache-Tabelle für Metadaten aus der TMDB API.
-- Verhindert redundante API-Calls und ermöglicht FK-Referenzen.
-- ----------------------------------------------------------
CREATE TABLE media (
  id           integer     PRIMARY KEY,          -- TMDB ID
  title        text        NOT NULL,
  type         text        NOT NULL,
  cover_url    text,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT valid_type      CHECK (type IN ('tv', 'movie')),
  CONSTRAINT cover_url_fmt   CHECK (cover_url IS NULL OR cover_url ~* '^https?://')
);

COMMENT ON TABLE media IS 'TMDB-Metadaten-Cache. Jeder Eintrag entspricht einem TMDB-Titel (TV oder Film).';
COMMENT ON COLUMN media.id IS 'TMDB ID – direkt übernommen, kein Auto-Increment.';

-- ----------------------------------------------------------
-- USER_WATCHLIST
-- Verknüpft Nutzer mit Medien + Tracking-Daten.
-- ----------------------------------------------------------
CREATE TABLE user_watchlist (
  id           bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      uuid        NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  media_id     integer     NOT NULL REFERENCES media(id)   ON DELETE CASCADE,
  status       text        NOT NULL DEFAULT 'plan_to_watch',
  rating       integer,
  notes        text,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),

  -- Jeder Nutzer kann jeden Titel nur einmal in der Watchlist haben
  UNIQUE (user_id, media_id),

  CONSTRAINT valid_status  CHECK (status IN ('plan_to_watch', 'watching', 'completed', 'dropped', 'on_hold')),
  CONSTRAINT valid_rating  CHECK (rating IS NULL OR (rating >= 1 AND rating <= 10)),
  CONSTRAINT notes_length  CHECK (notes IS NULL OR char_length(notes) <= 1000)
);

COMMENT ON TABLE user_watchlist IS 'Watchlist-Einträge pro Nutzer. Status-Enum und Rating 1-10.';
COMMENT ON COLUMN user_watchlist.status IS 'Erlaubte Werte: plan_to_watch | watching | completed | dropped | on_hold';

-- ----------------------------------------------------------
-- REVIEWS
-- Community-Bewertungen mit Spoiler-Flag.
-- UNIQUE(user_id, media_id): Ein Review pro Nutzer pro Titel.
-- ----------------------------------------------------------
CREATE TABLE reviews (
  id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      uuid        NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  media_id     integer     NOT NULL REFERENCES media(id)   ON DELETE CASCADE,  -- FK! Vorher fehlte das
  rating       integer     NOT NULL,
  content      text        NOT NULL,
  is_spoiler   boolean     NOT NULL DEFAULT false,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),

  -- Ein Nutzer kann jeden Titel nur einmal reviewen
  UNIQUE (user_id, media_id),

  CONSTRAINT valid_rating      CHECK (rating >= 1 AND rating <= 10),
  CONSTRAINT content_length    CHECK (char_length(content) BETWEEN 10 AND 5000),
  CONSTRAINT content_not_empty CHECK (trim(content) != '')
);

COMMENT ON TABLE reviews IS 'Community-Reviews. Max. 1 Review pro Nutzer pro Titel (UNIQUE-Constraint).';
COMMENT ON COLUMN reviews.media_id IS 'FK auf media(id) – Waise-Reviews sind damit ausgeschlossen.';

-- ----------------------------------------------------------
-- CUSTOM_LISTS
-- Nutzerdefinierte kuratierte Listen.
-- ----------------------------------------------------------
CREATE TABLE custom_lists (
  id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      uuid        NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  name         text        NOT NULL,
  description  text,
  is_public    boolean     NOT NULL DEFAULT false,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT name_length        CHECK (char_length(name) BETWEEN 1 AND 100),
  CONSTRAINT name_not_empty     CHECK (trim(name) != ''),
  CONSTRAINT desc_length        CHECK (description IS NULL OR char_length(description) <= 500)
);

COMMENT ON TABLE custom_lists IS 'Nutzerdefinierte Listen (z.B. "Top 10 Isekai"). is_public=true macht sie für alle sichtbar.';

-- ----------------------------------------------------------
-- CUSTOM_LIST_ITEMS
-- Medien innerhalb einer Liste, mit sortierbarer Reihenfolge.
-- ----------------------------------------------------------
CREATE TABLE custom_list_items (
  id           bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  list_id      uuid        NOT NULL REFERENCES custom_lists(id) ON DELETE CASCADE,
  media_id     integer     NOT NULL REFERENCES media(id)        ON DELETE CASCADE,
  sort_order   integer     NOT NULL DEFAULT 0,
  added_at     timestamptz NOT NULL DEFAULT now(),

  UNIQUE (list_id, media_id)
);

COMMENT ON TABLE custom_list_items IS 'Medien innerhalb einer Custom List. sort_order ermöglicht manuelle Reihenfolge.';

-- ----------------------------------------------------------
-- NOTIFICATIONS
-- Interne App-Benachrichtigungen pro Nutzer.
-- ----------------------------------------------------------
CREATE TABLE notifications (
  id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      uuid        NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  type         text        NOT NULL DEFAULT 'info',
  title        text        NOT NULL,
  message      text        NOT NULL,
  link         text,                             -- Optionaler Deep-Link (z.B. /media/12345)
  is_read      boolean     NOT NULL DEFAULT false,
  created_at   timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT valid_type       CHECK (type IN ('info', 'success', 'warning', 'new_episode', 'review_reply')),
  CONSTRAINT title_length     CHECK (char_length(title) BETWEEN 1 AND 200),
  CONSTRAINT message_length   CHECK (char_length(message) BETWEEN 1 AND 1000),
  CONSTRAINT link_fmt         CHECK (link IS NULL OR link ~* '^(https?://|/)'),
  CONSTRAINT title_not_empty  CHECK (trim(title) != ''),
  CONSTRAINT msg_not_empty    CHECK (trim(message) != '')
);

COMMENT ON TABLE notifications IS 'App-Benachrichtigungen. Typen: info | success | warning | new_episode | review_reply.';
COMMENT ON COLUMN notifications.link IS 'Optionaler Deep-Link – relativ (beginnt mit /) oder absolut (http/https).';
